rate: 10
Robot1_controller:
  type: effort_controllers/JointTrajectoryController
  joints:
    - rob1_shoulder_pan_joint
    - rob1_shoulder_lift_joint
    - rob1_elbow_joint
    - rob1_wrist_1_joint
    - rob1_wrist_2_joint
    - rob1_wrist_3_joint
  gains: # Required because we're controlling an effort interface
    rob1_shoulder_pan_joint: {p: 20000,  d: 500, i: 10, i_clamp: 1}
    rob1_shoulder_lift_joint: {p: 20000,  d: 500, i: 10, i_clamp: 1}
    rob1_elbow_joint: {p: 20000,  d: 500, i: 10, i_clamp: 1}
    rob1_wrist_1_joint: {p: 500,  d: 10, i: 1, i_clamp: 1}
    rob1_wrist_2_joint: {p: 500,  d: 10, i: 1, i_clamp: 1}
    rob1_wrist_3_joint: {p: 10,  d: 0.1, i: 0, i_clamp: 1} 
  constraints:
    #goal_time: 0.6
    stopped_velocity_tolerance: 0
    rob1_shoulder_pan_joint: {trajectory: 0.1, goal: 0.1}
    rob1_shoulder_lift_joint: {trajectory: 0.1, goal: 0.1}
    rob1_elbow_joint: {trajectory: 0.1, goal: 0.1}
    rob1_wrist_1_joint: {trajectory: 0.1, goal: 0.1}
    rob1_wrist_2_joint: {trajectory: 0.1, goal: 0.1}
    rob1_wrist_3_joint: {trajectory: 0.1, goal: 0.1}
  #stop_trajectory_duration: 0.5
  state_publish_rate:  20
  action_monitor_rate: 20
Robot2_controller:
  type: effort_controllers/JointTrajectoryController
  joints:
    - rob2_shoulder_pan_joint
    - rob2_shoulder_lift_joint
    - rob2_elbow_joint
    - rob2_wrist_1_joint
    - rob2_wrist_2_joint
    - rob2_wrist_3_joint
  gains: # Required because we're controlling an effort interface
    rob2_shoulder_pan_joint: {p: 20000,  d: 500, i: 10, i_clamp: 1}
    rob2_shoulder_lift_joint: {p: 20000,  d: 500, i: 10, i_clamp: 1}
    rob2_elbow_joint: {p: 20000,  d: 500, i: 10, i_clamp: 1}
    rob2_wrist_1_joint: {p: 500,  d: 10, i: 1, i_clamp: 1}
    rob2_wrist_2_joint: {p: 500,  d: 10, i: 1, i_clamp: 1}
    rob2_wrist_3_joint: {p: 10,  d: 0.1, i: 0, i_clamp: 1} 
  constraints:
    #goal_time: 0.6
    stopped_velocity_tolerance: 0
    rob2_shoulder_pan_joint: {trajectory: 0.1, goal: 0.1}
    rob2_shoulder_lift_joint: {trajectory: 0.1, goal: 0.1}
    rob2_elbow_joint: {trajectory: 0.1, goal: 0.1}
    rob2_wrist_1_joint: {trajectory: 0.1, goal: 0.1}
    rob2_wrist_2_joint: {trajectory: 0.1, goal: 0.1}
    rob2_wrist_3_joint: {trajectory: 0.1, goal: 0.1}
  #stop_trajectory_duration: 0.5
  state_publish_rate:  20
  action_monitor_rate: 20
Robots_all_controller:
  type: effort_controllers/JointTrajectoryController
  joints:
    - rob1_shoulder_pan_joint
    - rob1_shoulder_lift_joint
    - rob1_elbow_joint
    - rob1_wrist_1_joint
    - rob1_wrist_2_joint
    - rob1_wrist_3_joint
    - rob2_shoulder_pan_joint
    - rob2_shoulder_lift_joint
    - rob2_elbow_joint
    - rob2_wrist_1_joint
    - rob2_wrist_2_joint
    - rob2_wrist_3_joint
  gains: # Required because we're controlling an effort interface
    rob1_shoulder_pan_joint: {p: 20000,  d: 500, i: 10, i_clamp: 1}
    rob1_shoulder_lift_joint: {p: 20000,  d: 500, i: 10, i_clamp: 1}
    rob1_elbow_joint: {p: 20000,  d: 500, i: 10, i_clamp: 1}
    rob1_wrist_1_joint: {p: 500,  d: 10, i: 1, i_clamp: 1}
    rob1_wrist_2_joint: {p: 500,  d: 10, i: 1, i_clamp: 1}
    rob1_wrist_3_joint: {p: 10,  d: 0.1, i: 0, i_clamp: 1} 
    rob2_shoulder_pan_joint: {p: 20000,  d: 500, i: 10, i_clamp: 1}
    rob2_shoulder_lift_joint: {p: 20000,  d: 500, i: 10, i_clamp: 1}
    rob2_elbow_joint: {p: 20000,  d: 500, i: 10, i_clamp: 1}
    rob2_wrist_1_joint: {p: 500,  d: 10, i: 1, i_clamp: 1}
    rob2_wrist_2_joint: {p: 500,  d: 10, i: 1, i_clamp: 1}
    rob2_wrist_3_joint: {p: 10,  d: 0.1, i: 0, i_clamp: 1} 
  constraints:
    #goal_time: 0.6
    stopped_velocity_tolerance: 0
    rob1_shoulder_pan_joint: {trajectory: 0.1, goal: 0.1}
    rob1_shoulder_lift_joint: {trajectory: 0.1, goal: 0.1}
    rob1_elbow_joint: {trajectory: 0.1, goal: 0.1}
    rob1_wrist_1_joint: {trajectory: 0.1, goal: 0.1}
    rob1_wrist_2_joint: {trajectory: 0.1, goal: 0.1}
    rob1_wrist_3_joint: {trajectory: 0.1, goal: 0.1}
    rob2_shoulder_pan_joint: {trajectory: 0.1, goal: 0.1}
    rob2_shoulder_lift_joint: {trajectory: 0.1, goal: 0.1}
    rob2_elbow_joint: {trajectory: 0.1, goal: 0.1}
    rob2_wrist_1_joint: {trajectory: 0.1, goal: 0.1}
    rob2_wrist_2_joint: {trajectory: 0.1, goal: 0.1}
    rob2_wrist_3_joint: {trajectory: 0.1, goal: 0.1}
  #stop_trajectory_duration: 0.5
  state_publish_rate:  20
  action_monitor_rate: 20
joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 10